export const actionType = {
  START_REFRESH_STUDENT_LIST: "START_REFRESH_STUDENT_LIST",
  REFRESH_STUDENT_LIST_SUCCESS: "REFRESH_STUDENT_LIST_SUCCESS",
  REFRESH_STUDENT_LIST_FAIL: "REFRESH_STUDENT_LIST_FAIL",
  //   REFRESH_STUDENT_LIST_SUCCESS: "REFRESH_STUDENT_LIST_SUCCESS",
  MOVE_EXACTLY_TO_PAGE: "MOVE_EXACTLY_TO_PAGE",
  CHANGE_SEARCHING_VALUE: "CHANGE_SEARCHING_VALUE",
  IS_LOADING: "IS_LOADING",
  IS_ERROR: "IS_ERROR",
  MODIFY_STUDENT: {
    SAVE: "EDIT_STUDENT",
  },
  ADD_STUDENT: {
    SAVE: "SAVE_NEW_STUDENT",
  },
};
